services:
  - type: web
    name: focus-board
    env: ruby
    region: oregon
    plan: free
    branch: main
    buildCommand: "./bin/build"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: RAILS_MASTER_KEY
        sync: false
