default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV ["DATABASE_URL"] %>

development:
  <<: *default

test:
  <<: *default

production:
  primary: &primary_production
    <<: *default
  url: <%= ENV["DATABASE_URL"] %>
